src/Wellbeing.Data.Client/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Wellbeing.Data.Client.Models;
using Wellbeing.Data.Service.Interfaces;

namespace Wellbeing.Data.Client.Controllers
{
	public class ReportsController : Controller
	{
		private readonly IActivityService _activityService;
		private string _googleApiKey;

		public ReportsController(IActivityService activityService, IConfiguration configuration)
		{
			_activityService = activityService;
			_googleApiKey = configuration["GoogleMapsAPI"];
		}

		public IActionResult Index()
		{
			return Redirect("/Search");
		}

		[HttpPost]
		public IActionResult Print()
		{
			ViewBag.GoogleApiKey = _googleApiKey;

			var activitiesToPrint = new List<Guid>();
			foreach (var item in HttpContext.Request.Form)
			{
				if (item.Key.Contains("printId_"))
				{
					if (Guid.TryParse(item.Value, out var activityId))
					{
						activitiesToPrint.Add(activityId);
					}
				}
			}

			if (activitiesToPrint.Count == 0)
			{
				return RedirectToAction("Search", "Home");
			}

			var activities = _activityService.GetActivitiesToPrint(activitiesToPrint)
				.Select(x => new ActivityViewModel()
				{
					Id = x.Id,
					Title = x.Title,
					Description = x.Description,
					StatusId = x.StatusId,
					Contact = x.Contact,
					DateTimeDescription = x.DateTimeDescription,
					LocationDescription = x.LocationDescription,
					LocationPostcode = x.LocationPostcode,
					DateCreated = x.DateCreated,
					CreatedBy = x.CreatedBy,
					DateDeleted = x.DateDeleted,
					UpdatedBy = x.UpdatedBy,
					OrganisationId = x.OrganisationId,
					OrganisationName = x.OrganisationName,
					OrganisationWebsite = x.OrganisationWebsite,
					OrganisationWebsiteLink = x.OrganisationWebsiteLink
				}).ToList();


			return View(activities);

		}
	}
}

src/Wellbeing.Data.Client/Views/Reports/Print.cshtml
@using System.Data.Common
@model List<Wellbeing.Data.Client.Models.ActivityViewModel>
@{
    ViewData["Title"] = "Wellbeing Report";
    Layout = "~/Views/Shared/_ReportLayout.cshtml";
}

<header class="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-11 col-11 col-sm-11">
                <div class="hd-img-icon">
                    <a href="" class="desktop-img">
                        <img class="" src="~/public/images/hand-btn.jpg">
                    </a>
                    <a href="" class="mobile-img">
                        <img class="" src="~/public/images/mobile-hand-btn.jpg">
                    </a>
                </div>
            </div>
            <div class="col-md-1 col-1 col-sm-1">
                <div class="">
                    <p>
                        <a href="javascript:window.print()" class="btn btn-success btn-lg btn-print-icon">
                            <span class="glyphicon glyphicon-print"></span> Print
                        </a>
                    </p>
                </div>
            </div>

        </div>
    </div>
    
 </header>
 
<div class="table-responsive-sm activityList">

    <div class="search-treatment-details">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-12 col-sm-12">
                    <h2>Wellbeing Report</h2>           
                </div>
            </div>
        </div>
     </div>
    @foreach (var item in Model)
    {
        <div class="search-treatment-details">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-12 col-sm-12">
                        <div class="st-detail-right">
                            <div class="row border-bottom-row">
                                <div class="col-md-6 col-12 text-md-left">
                                    <h5>Date: <a href="">@item.DateTimeDescription</a> </h5>
                                </div>
                                <div class="col-md-6 col-12 text-md-right">
                                    <h5>Venue: <a href="">@item.LocationPostcode</a> </h5>
                                </div>
                            </div>
                            <div class="details-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h5>@item.Title</h5>
                                    </div>
                                    <div class="col-md-6 text-md-right">
                                        <a href="" data-activity-id="@item.Id" data-report-url="@Url.Action("Print", "Reports")" class="remove-from-report"><i class="icon ion-md-close-circle"></i></a>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p>
                                            @item.Description
                                        </p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div id="map-canvas-@item.Id" class="col-md-12 map-canvas">
                                        Map canvas
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <h5>Further details</h5>
                                        </div>
                                        <div class="col-md-6">
                                            <dl class="dl-vertical">
                                                <dt>
                                                    @Html.DisplayNameFor(model => model[0].OrganisationName)
                                                </dt>
                                                <dd>
                                                    @Html.DisplayFor(model => item.OrganisationName)
                                                </dd>
                                                <dt>
                                                    @Html.DisplayNameFor(model => model[0].LocationDescription)
                                                </dt>
                                                <dd>
                                                    @Html.DisplayFor(model => item.LocationDescription)
                                                </dd>
                                                <dt>
                                                    @Html.DisplayNameFor(model => model[0].Contact)
                                                </dt>
                                                <dd>
                                                    @Html.DisplayFor(model => item.Contact)
                                                </dd>
                                            </dl>
                                        </div>
                                        <div class="col-md-6">
                                            <dl class="dl-vertical">
                                                <dt>
                                                    @Html.DisplayNameFor(model => item.OrganisationWebsite)
                                                </dt>
                                                <dd>
                                                    <a target="_blank" href="@Html.DisplayFor(model => item.OrganisationWebsiteLink)">@Html.DisplayFor(model => item.OrganisationWebsite)</a>
                                                </dd>
                                            </dl>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pagebreak"> </div>
        </div>
    }
</div>
@section Styles {
    <link href="@Url.Content("~/public/assets/css/print.css")" rel="stylesheet" type="text/css" />
}
@section Scripts{
    @{
        var key = ViewBag.GoogleApiKey;
    }

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=@key&callback=initializeMaps"
            type="text/javascript"></script>
    <script language="javascript">

            var _maps = [];
            var _geocoder;
            var _items;

            function getDefaultMapOptions() {
                // default location to start on
                var latlng = new google.maps.LatLng(51.059802, -1.310570);
                var mapOptions = {
                    zoom: 14,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                return mapOptions;
            }

            function initializeMaps() {
                _items = @Html.Raw(Json.Serialize(Model));

                if (!_items || _items.length === 0) return;

                _geocoder = new google.maps.Geocoder();

                for (var i = 0; i < _items.length; i++) {
                    _maps[i] = new google.maps.Map(document.getElementById('map-canvas-' + _items[i].id), getDefaultMapOptions());
                    setMapAddress(_items[i].locationPostcode, i);
                }
                // once set up, zoom to marker
            }

            function setMapAddress(address, index) {
                if (!!address) {
                    _geocoder.geocode({ 'address': address },
                        function(results, status) {
                            if (status == google.maps.GeocoderStatus.OK) {
                                _maps[index].setCenter(results[0].geometry.location);
                                var marker = new google.maps.Marker({
                                    map: _maps[index],
                                    position: results[0].geometry.location
                                });
                            } else {
                                alert('Geocode was not successful for the following reason: ' + status);
                            }
                        });
                }
            }
    </script>
    <script language="javascript">
        $(document).ready(function () {
            $('a.remove-from-report').click(function (evt) {
                evt.preventDefault();
                if (window.messageBus) {
                    var activityId = $(this).attr('data-activity-id');
                    var reportUrl = $(this).attr('data-report-url');
                    window.messageBus.reportRemoved.dispatch(activityId, reportUrl);
                }
            });
        });
    </script>
}