src/Wellbeing.Data.Client/Controllers/FeedbacksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Wellbeing.Data.Client.Extensions;
using Wellbeing.Data.Client.Models;
using Wellbeing.Data.Repository;
using Wellbeing.Data.Repository.Models;
using Wellbeing.Data.Service.Interfaces;
using Wellbeing.Data.Service.Models;

namespace Wellbeing.Data.Client.Controllers
{
    public class FeedbacksController : Controller
    {
	    private readonly WellbeingDbContext _context;
	    private readonly INotificationService _notificationService;
	    private ILogger _logger;

		public FeedbacksController(WellbeingDbContext context, INotificationService notificationService, ILogger<FeedbacksController> logger)
		{
			_context = context;
			_logger = logger;
			_notificationService = notificationService;
		}

	    public async Task<IActionResult> Index()
        {
	        var feedbackVms = await _context.Feedbacks
		        .OrderByDescending(x => x.DateCreated)
		        .Select(x => new FeedbackViewModel
		        {
			        Id = x.Id,
					Comment = x.Comment,
					Contact = x.Contact,
					DateCreated = x.DateCreated,
					Email = x.Email,
					NotificationSent = x.NotificationSent,
					Recipients = x.Recipients
		        })
		        .ToListAsync();

	        return View(feedbackVms);
        }

	    // GET: Activities/Details/5
	    public async Task<IActionResult> Details(Guid? id)
	    {
		    if (id == null)
		    {
			    return NotFound();
		    }



		    var feedback = await  _context.Feedbacks.FirstOrDefaultAsync(x => x.Id == (Guid) id);

		    var feedbackVm = new FeedbackViewModel()
		    {
			    Id = feedback.Id,
			    Contact= feedback.Contact,
			    Email= feedback.Email,
			    Comment= feedback.Comment,
			    DateCreated = feedback.DateCreated,
		    };


		    return View(feedbackVm);
	    }


		// GET: Activities/Create
		public IActionResult Create()
		{
			var vm = new FeedbackViewModel();
			return View(vm);
		}


		// POST: Activities/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Contact,Email,Comment")] FeedbackViewModel vm, IFormCollection formCollection)
		{
			if (!ModelState.IsValid) return View(vm);

			var creationDate = DateTime.Now;

			var model = new Feedback()
			{
				Id = Guid.NewGuid(),
				Contact = vm.Contact,
				Email = vm.Email,
				Comment = vm.Comment,
				DateCreated = creationDate,
			};
			await _notificationService.NotifyOnFeedbackCreated(model);

			_context.Add(model);

			await _context.SaveChangesAsync();
			if (User.Identity.IsAuthenticated)
			{
				return RedirectToAction("Index", "Activities");
			}

			return RedirectToAction("Search", "Home");
		}
	}
}

src/Wellbeing.Data.Client/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Wellbeing.Data.Client.Models;
using Wellbeing.Data.Service.Interfaces;

namespace Wellbeing.Data.Client.Controllers
{
	public class ReportsController : Controller
	{
		private readonly IActivityService _activityService;
		private string _googleApiKey;

		public ReportsController(IActivityService activityService, IConfiguration configuration)
		{
			_activityService = activityService;
			_googleApiKey = configuration["GoogleMapsAPI"];
		}

		public IActionResult Index()
		{
			return Redirect("/Search");
		}

		[HttpPost]
		public IActionResult Print()
		{
			ViewBag.GoogleApiKey = _googleApiKey;

			var activitiesToPrint = new List<Guid>();
			foreach (var item in HttpContext.Request.Form)
			{
				if (item.Key.Contains("printId_"))
				{
					if (Guid.TryParse(item.Value, out var activityId))
					{
						activitiesToPrint.Add(activityId);
					}
				}
			}

			if (activitiesToPrint.Count == 0)
			{
				return RedirectToAction("Search", "Home");
			}

			var activities = _activityService.GetActivitiesToPrint(activitiesToPrint)
				.Select(x => new ActivityViewModel()
				{
					Id = x.Id,
					Title = x.Title,
					Description = x.Description,
					StatusId = x.StatusId,
					Contact = x.Contact,
					DateTimeDescription = x.DateTimeDescription,
					LocationDescription = x.LocationDescription,
					LocationPostcode = x.LocationPostcode,
					DateCreated = x.DateCreated,
					CreatedBy = x.CreatedBy,
					DateDeleted = x.DateDeleted,
					UpdatedBy = x.UpdatedBy,
					OrganisationId = x.OrganisationId,
					OrganisationName = x.OrganisationName,
					OrganisationWebsite = x.OrganisationWebsite,
					OrganisationWebsiteLink = x.OrganisationWebsiteLink
				}).ToList();


			return View(activities);

		}
	}
}

src/Wellbeing.Data.Client/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Wellbeing.Data.Repository;
using Wellbeing.Data.Repository.Models;

namespace Wellbeing.Data.Client.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        private readonly WellbeingDbContext _context;

        public RolesController(WellbeingDbContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .SingleOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Role role)
        {
            if (ModelState.IsValid)
            {
                role.Id = Guid.NewGuid();
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.SingleOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name")] Role role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .SingleOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var role = await _context.Roles.SingleOrDefaultAsync(m => m.Id == id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(Guid id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

src/Wellbeing.Data.Client/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Wellbeing.Data.Repository;
using Wellbeing.Data.Repository.Models;
using Wellbeing.Data.Service;
using Wellbeing.Data.Service.Interfaces;
using Wellbeing.Data.Service.Models;

namespace Wellbeing.Data.Client.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly WellbeingDbContext _context;
        private readonly ISecurityService _securityService;
        private readonly IUserService _userService;
        private readonly IUserMappingService _userMappingService;

        public UsersController(WellbeingDbContext context, ISecurityService securityService, IUserService userService, IUserMappingService userMappingService)
        {
            _context = context;
            _securityService = securityService;
            _userService = userService;
            _userMappingService = userMappingService;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAll();           
            return View(users);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userService.GetById(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            
            ViewBag.Organisation = new SelectList(_context.Organisations.OrderBy(o => o.Name), "Id", "Name", 0);
            ViewBag.Roles = new SelectList(_context.Roles, "Id", "Name");

            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Name, Email, Password, RoleId, UserCompanyId, NotifyOnActivityUpdate")] WellbeingUser user)
        {
           
            var newUser = new User();
      
            newUser.Id = Guid.NewGuid();
            newUser.Name = user.Name;
            newUser.Email = user.Email;
            newUser.DateCreated = DateTime.Now;
            newUser.DateUpdated = DateTime.Now;
            newUser.NotifyOnActivityUpdate = user.NotifyOnActivityUpdate;

            var role = _context.Roles.FirstOrDefault(r => r.Id == user.RoleId);
            if (role != null)
                newUser.Role = role;

            var company = _context.Organisations.FirstOrDefault(o => o.Id == user.UserCompanyId);
            if (company != null)
                newUser.UserCompany = company;

            if (!string.IsNullOrEmpty(user.Password))
                newUser.Password = _securityService.HashText(user.Password, user.Email);

            _context.Add(newUser);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userService.GetById(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            ViewBag.Organisation = new SelectList(_context.Organisations.OrderBy(o => o.Name), "Id", "Name", 0);
            ViewBag.Roles = new SelectList(_context.Roles, "Id", "Name", user.RoleId);

            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id, Name, Email, Password, RoleId, UserCompanyId, NotifyOnActivityUpdate")] WellbeingUser user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingUser = _context.Users.FirstOrDefault(u => u.Id == id);

                    if (existingUser != null)
                    {
                        existingUser.Name = user.Name;
                        existingUser.NotifyOnActivityUpdate = user.NotifyOnActivityUpdate;
                        var role = _context.Roles.FirstOrDefault(r => r.Id == user.RoleId);
                        if (role != null)
                            existingUser.Role = role;

                        var company = _context.Organisations.FirstOrDefault(o => o.Id == user.UserCompanyId);
                        if (company != null)
                            existingUser.UserCompany = company;

                        if (!string.IsNullOrEmpty(user.Password))
                            existingUser.Password = _securityService.HashText(user.Password, existingUser.Email);

                        existingUser.DateUpdated = DateTime.Now;
                        
                        _context.Update(existingUser);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(Guid id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

src/Wellbeing.Data.Client/Views/Shared/_Layout.cshtml
@* @inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet *@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap-4.0.0-dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap-4.0.0-dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", false)
    @* @Html.Raw(JavaScriptSnippet.FullScript) *@
</head>
<body>
        <nav id="myNav" class="navbar navbar-expand-lg navbar-dark navbar-fixed-top">
            <div class="d-flex p-1 mr-2">
                <a href="/" title="St John's Winchester" class="navbar-brand">
                    <img src="@Url.Content("~/Images/logo.png")"
                         alt="St John's Winchester"
                         title="St John's Winchester">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarText">

                @if (User.Identity.IsAuthenticated)
                {
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Search" asp-controller="Home">Search</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Activities">Activities</a>
                    </li>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="ActivityTypes">Activity Types</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Organisations">Organisations</a>
                    </li>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Roles">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Feedbacks">Feedback</a>
                        </li>
                    }
                </ul>
                    <form class="form-inline" asp-controller="Account" asp-action="LogOff">
                        <button class="btn btn-secondary" type="submit">Logout</button>
                    </form>
                }
                else
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Home" asp-controller="Home">Search</a>
                        </li>
                    </ul>

                        }
                </div>
        </nav> 
    
    <div class="container-fluid body-content py-3 fill">
        @RenderBody()
    </div>
    <footer class="footer mt-2">
        <div class="container">
            <span class="text-muted">&copy; 2018 - Wellbeing Data Admin</span>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap-4.0.0-dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap-4.0.0-dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>*@

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Wellbeing.Data.Client/Views/Shared/_ReportLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130422551-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-130422551-1');
    </script>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="icon" href="~/public/images/favicon.ico">
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap-4.0.0-dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />*@
        <!-- Bootstrap core CSS -->
        <link href="~/public/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/public/assets/css/bootstrap-grid.min.css" rel="stylesheet">
        <link href="~/public/assets/css/styles.css" rel="stylesheet">
        <link href="~/public/assets/css/font-awesome.min.css" rel="stylesheet">
        <link href="~/public/assets/css/ionicons.min.css" rel="stylesheet">
        <link href="~/public/assets/css/dropdown-tree.css" rel="stylesheet">
        <link href="~/lib/ionicons/css/ionicons.min.css"  rel="stylesheet"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/public/assets/css/bootstrap.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/public/assets/css/bootstrap-grid.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/public/assets/css/styles.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/public/assets/css/font-awesome.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/public/assets/css/ionicons.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/public/assets/css/dropdown-tree.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/ionicons/css/ionicons.min.css"  asp-append-version="true"/>
    </environment>
    @RenderSection("Styles", false)

</head>
<body>

    <main role="main">
        @RenderBody()
    </main>



        <environment include="Development">
            <!-- Bootstrap core JavaScript   ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap-4.0.0-dist/js/bootstrap.js"></script>
            <script src="~/lib/bootstrap-4.0.0-dist/js/bootstrap.js"></script>
            <script src="~/lib/js-signals/js-signals.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/public/assets/js/popper.min.js"></script>
            <script src="~/public/assets/js/dropdown/dropdowntree.js"></script>
            <script src="~/public/assets/js/main.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossOrigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossOrigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossOrigin="anonymous"></script>
            <script src="~/public/assets/js/dropdown/dropdowntree.js" asp-append-version="true"></script>
            <script src="~/public/assets/js/js-signals.min.js" asp-append-version="true"></script>
            <script src="~/public/assets/js/main.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>