src/Wellbeing.Data.Client/Models/ActivityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Wellbeing.Data.Repository.Models;
using Wellbeing.Data.Service.Models;

namespace Wellbeing.Data.Client.Models
{
    public class ActivityViewModel
    {

        public ActivityViewModel()
        {
            ActivityTypeList = new List<CheckboxListItem>();
			OrganisationList = new List<CheckboxListItem>();
        }

        public Guid Id { get; set; }

        public bool UserCanEdit { get; set; }

        [DisplayName("When")]
        public string DateTimeDescription { get; set; }
        [Required]
        public string Description { get; set; }

        [DisplayName("Location")]
        public string LocationDescription { get; set; }

        [DisplayName("Postcode")]
        public string LocationPostcode { get; set; }

        [DisplayName("Organisation")]
        public Guid? OrganisationId { get; set; }

        [DisplayName("Organisation provider")]
        public string OrganisationName { get; set; }

        [DisplayName("Organisation Website")]
        public string OrganisationWebsite { get; set; }

        public string OrganisationWebsiteLink { get; set; }

        [DisplayName("Approval Status")]
        public int StatusId { get; set; }

        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string Title { get; set; }

        public string Contact { get; set; }

        public DateTime DateCreated { get; set; }
        public User CreatedBy { get; set; }

        [DisplayName("User Organisation")]
        public string UserOrganisationName { get; set; }

        
        public DateTime? DateUpdated { get; set; }
        public User UpdatedBy { get; set; }

        public DateTime? DateDeleted { get; set; }

        public ActivityType ActivityType { get; set; }

        public IList<CheckboxListItem> ActivityTypeList { get; set; }
		public IList<CheckboxListItem> OrganisationList { get; set; }
        public ICollection<ActivityClassifications> ActivityClassifications { get; set; }

        [DisplayName("Primary Activity Type")]
        public ActivityType PrimaryClassification { get; set; }

        public IList<ActivityTypeInfo> ActivityTypeAndAncestors { get; set; }
    }
}

src/Wellbeing.Data.Client/Controllers/ActivitiesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ValueGeneration.Internal;
using Microsoft.Extensions.Logging;
using Wellbeing.Data.Client.Extensions;
using Wellbeing.Data.Client.Interfaces;
using Wellbeing.Data.Client.Models;
using Wellbeing.Data.Repository;
using Wellbeing.Data.Repository.Models;
using Wellbeing.Data.Service;
using Wellbeing.Data.Service.Interfaces;
using Wellbeing.Data.Service.Models;

namespace Wellbeing.Data.Client.Controllers
{
    [Authorize]
    public class ActivitiesController : Controller
    {
        private readonly WellbeingDbContext _context;
        private IActivityTypeService _activityTypeService;
        private IActivityService _activityService;
        private readonly INotificationService _notificationService;
        private IActivitiesDataCache _activitiesDataCache;
        IUserService _userService;
        ILogger _logger;

        public ActivitiesController(WellbeingDbContext context, IActivityTypeService activityTypeService, IUserService userService
            , IActivityService activityService, ILogger<AccountController> logger, IActivitiesDataCache activitiesDataCache, INotificationService notificationService)
        {
            _context = context;
            _activityTypeService = activityTypeService;
            _userService = userService;
            _activityService = activityService;
            _activitiesDataCache = activitiesDataCache;
            _notificationService = notificationService;
            _logger = logger;
        }

        // GET: Activities
        public async Task<IActionResult> Index(int page = 1)
        {
            var rowsToDisplay = 20;
            Guid? eventProviderFilter = null;
            Guid? dataProviderFilter = null;
            Guid? activityTypeFilter = null;
            int? statusFilter = null;
            string searchText = null;
            string[] keywords = null;

            _logger.LogDebug($"About to get activities data {DateTime.Now}");

            var activities = new List<WellbeingActivity>();
            if (Request.Query.Any())
            {
                if (!string.IsNullOrEmpty(Request.Query["search"]))
                {
                    searchText = Request.Query["search"];
                    var search = searchText ?? string.Empty;
                    keywords = search.Split(new char[] { ' ' });
                }

                if (!string.IsNullOrEmpty(Request.Query["eventProviderOrganisationFilter"])) 
                    eventProviderFilter = Guid.Parse(Request.Query["eventProviderOrganisationFilter"]);

                if (!string.IsNullOrEmpty(Request.Query["dataProviderOrganisationFilter"]))
                    dataProviderFilter = Guid.Parse(Request.Query["dataProviderOrganisationFilter"]);

                if (!string.IsNullOrEmpty(Request.Query["activityTypeFilter"]))
                    activityTypeFilter = Guid.Parse(Request.Query["activityTypeFilter"]);

                if (!string.IsNullOrEmpty(Request.Query["statusFilter"]))
                    statusFilter = int.Parse(Request.Query["statusFilter"]);

                // invoked by pager - build query from querystring
                activities = _activityService.GetActivities(keywords, eventProviderFilter, dataProviderFilter, statusFilter, activityTypeFilter);

            }

            _logger.LogDebug($"About to got activities data {DateTime.Now}");

            var userCompanyId = Guid.Parse(User.FindFirst("CompanyOrganisationId").Value);

            var activitiesVm = activities
                .Select(a =>
                    new ActivityViewModel()
                    {
                        Id = a.Id,
                        Title = a.Title,
                        DateTimeDescription = a.DateTimeDescription,
                        Contact = a.Contact,
                        StatusId = a.StatusId,
                        CreatedBy = a.CreatedBy,
                        DateCreated = a.DateCreated,
                        UpdatedBy = a.UpdatedBy,
                        DateUpdated = a.DateUpdated,
                        Description = a.Description,
                        OrganisationName = a.OrganisationName,
                        ActivityType = a.ActivityType,
                        UserCanEdit = a.UserOrganisationId == userCompanyId || User.IsInRole("SuperAdmin"),
                        PrimaryClassification = a.ActivityType == null
                            ? null
                            : ActivityTypeHelper.GetRootType(_context, a.ActivityType).Result
                    }
                );

            var orgList = new SelectList(_activitiesDataCache.Organisations, "Id", "Name");
            
            var activityTypeList = new SelectList(_activitiesDataCache.SelectListActivityTypeTree, "Value", "Text");

            var pagedData = activitiesVm.AsQueryable().GetPagedDataEntry(page, rowsToDisplay);
            pagedData.EventProviderOrganisationList = orgList;

            if (eventProviderFilter.HasValue)
                pagedData.EventProviderOrganisationFilter = eventProviderFilter.Value;

            if (dataProviderFilter.HasValue)
                pagedData.DataProviderOrganisationFilter = dataProviderFilter.Value;

            if (activityTypeFilter.HasValue)
                pagedData.ActivityTypeFilter = activityTypeFilter.Value;

            if (statusFilter.HasValue)
                pagedData.StatusFilter = statusFilter.Value;

            if (!string.IsNullOrEmpty(searchText))
            {
                pagedData.Search = searchText;
            }

            pagedData.DataProviderOrganisationList = orgList;
            pagedData.StatusList = new SelectList(ActivityHelper.GetStatusList(), "Value", "Text");
            pagedData.ActivityTypeList = activityTypeList;
            pagedData.HaveSearched = false;            

            return View(pagedData);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string search, Guid eventProviderOrganisationFilter, Guid dataProviderOrganisationFilter, int? statusFilter, Guid activityTypeFilter, int page=1)
        {
            var rowsToDisplay = 20;
            _logger.LogDebug($"About to get activities data {DateTime.Now}");
            search = search ?? string.Empty;
            var keywords = search.Split(new char[] { ' ' });

            var activities = _activityService.GetActivities(keywords, eventProviderOrganisationFilter, dataProviderOrganisationFilter, statusFilter, activityTypeFilter);
            
            _logger.LogDebug($"About to got activities data {DateTime.Now}");

            var userCompanyId = Guid.Parse(User.FindFirst("CompanyOrganisationId").Value);

            var activitiesVm = activities
                .Select(a =>
                    new ActivityViewModel()
                    {
                        Id = a.Id,
                        Title = a.Title,
                        DateTimeDescription = a.DateTimeDescription,
                        Contact = a.Contact,
                        StatusId = a.StatusId,
                        CreatedBy = a.CreatedBy,
                        DateCreated = a.DateCreated,
                        UpdatedBy = a.UpdatedBy,
                        DateUpdated = a.DateUpdated,
                        Description = a.Description,
                        OrganisationName = a.OrganisationName,
                        ActivityType = a.ActivityType,
                        UserCanEdit = a.UserOrganisationId == userCompanyId || User.IsInRole("SuperAdmin"),
                        PrimaryClassification = a.ActivityType == null
                            ? null
                            : ActivityTypeHelper.GetRootType(_context, a.ActivityType).Result
                    }
                );

            var orgList = new SelectList(_activitiesDataCache.Organisations, "Id", "Name", eventProviderOrganisationFilter);

            var activityTypeList = new SelectList(_activitiesDataCache.SelectListActivityTypeTree, "Value", "Text",
                activityTypeFilter);

            var pagedData = activitiesVm.AsQueryable().GetPagedDataEntry(page, rowsToDisplay);
            pagedData.EventProviderOrganisationList = orgList;
            pagedData.DataProviderOrganisationList = orgList;
            pagedData.StatusList = new SelectList(ActivityHelper.GetStatusList(), "Value", "Text", statusFilter.ToString());
            pagedData.ActivityTypeList = activityTypeList;
            pagedData.HaveSearched = false;
            pagedData.EventProviderOrganisationFilter = eventProviderOrganisationFilter;
            pagedData.DataProviderOrganisationFilter = dataProviderOrganisationFilter;
            pagedData.StatusFilter = statusFilter;
            pagedData.HaveSearched = true;
            pagedData.ActivityTypeFilter = activityTypeFilter;
            pagedData.Search = search;

            return View(pagedData);
        }
        // GET: Activities/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityTypeInfo = (_context.ActivityTypes.Select(x => new ActivityTypeInfo()
            {
                Id = x.Id,
                ParentId = x.ParentId,
                Description = x.Description,
                DateCreated = x.DateCreated,
                DateDeleted = x.DateDeleted
            }).ToList());


            var activity = _activityService.GetActivity(id.Value);

            var activityVm = new ActivityViewModel()
            {
                Id = activity.Id,
                Title = activity.Title,

src/Wellbeing.Data.Client/Views/Activities/Delete.cshtml
@model Wellbeing.Data.Repository.Models.Activity

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Activity</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Contact)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Contact)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DateTimeDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DateTimeDescription)
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LocationDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LocationDescription)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LocationPostcode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LocationPostcode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>
        </dl>
    </div>
</div>
<div>    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Wellbeing.Data.Client/Views/Activities/Details.cshtml
@model Wellbeing.Data.Client.Models.ActivityViewModel

@{
    ViewData["Title"] = "Details";
}

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" asp-action="Details" asp-controller="Activities" asp-route-id="@Model.Id">General</a>
    </li>

    <li class="nav-item">
        <a class="nav-link " asp-action="HistoryDetails" asp-controller="Activities" asp-route-id="@Model.Id">History</a>
    </li>
</ul>

<h2>Details of/Service</h2>
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Contact)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Contact)
            </dd>
        
            <dt>
                <label Types</label>
            </dt>
            <dd>
            @*@Html.DropDownList(Types", selectList, "Select type", new { @class = "form-control" })*@
            
                @foreach (var activtityType in Model.ActivityTypeList)
                {
                    var IdParts = activtityType.Id.Split("_");

                    <div class="tree-IdParts.Count()">
                        @if (activtityType.IsChecked)
                        {
                            @Html.CheckBox(activtityType.Id, new { @checked = "checked", @disabled="disabled"})
                            @activtityType.Display
                        }
                        else
                        {
                            //    @Html.CheckBox(activtityType.Id)
                        }
                        
                        @*<input type="checkbox" id="@activtityType.Id" /> @activtityType.Display*@
                    </div>
                }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTimeDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTimeDescription)
        </dd>
        </dl>
       
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt><label asp-for="OrganisationId" class="control-label"></label></dt>
            <dd>
                <select asp-for="OrganisationId" disabled class="form-control" asp-items="ViewBag.Organisation"></select>
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LocationDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LocationDescription)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LocationPostcode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LocationPostcode)
            </dd>
           
        </dl>


        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>        

        </dl>
    </div>
</div>
<div class="mb-2">
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-controller="Activities">Back to List</a>
</div>

src/Wellbeing.Data.Client/Views/Activities/Edit.cshtml
@model Wellbeing.Data.Client.Models.ActivityViewModel

@{
    ViewData["Title"] = "Edit - Activity/Service";
}
<style type="text/css">.details-header { margin-top: 15px; }</style>


<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" asp-action="Edit" asp-controller="Activities" asp-route-id="@Model.Id">General</a>
    </li>

    <li class="nav-item">
        <a class="nav-link " asp-action="HistoryEdit" asp-controller="Activities" asp-route-id="@Model.Id">History</a>
    </li>
</ul>

<form asp-action="Edit">
    
    <div class="row details-header">
        <div class="col-md-10">
            <h2 >Edit - Activity/Service</h2>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <input type="button" value="Close" onclick="location.href='@Url.Action("Index", "Activities")';return false;" class="btn btn-default" />
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control"/>
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OrganisationId" class="control-label"></label>
                <select asp-for="OrganisationId" class="form-control" asp-items="ViewBag.Organisation"></select>
            </div>

            <div class="form-group">
                <h3>Activity Types </h3>
                <label>Add new Activity Type</label>
                @*@Html.DropDownList("ActivityTypes", selectList, "Select activity type", new { @class = "form-control" })*@

                <div>
                    @foreach (var activtityType in Model.ActivityTypeList)
                    {
                        var activityIdParts = activtityType.Id.Split("_");

                        <div class="tree-@activityIdParts.Count()">
                            @if (activtityType.IsChecked)
                            {
                                @Html.CheckBox(activtityType.Id, new {@checked = "checked"})
                            }
                            else
                            {
                                @Html.CheckBox(activtityType.Id)
                            }
                            @activtityType.Display
                            @*<input type="checkbox" id="@activtityType.Id" /> @activtityType.Display*@
                        </div>
                    }
                </div>
            </div>

        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="DateTimeDescription" class="control-label"></label>
                <input asp-for="DateTimeDescription" class="form-control"/>
                <span asp-validation-for="DateTimeDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationDescription" class="control-label"></label>
                <textarea asp-for="LocationDescription" class="form-control" rows="4"></textarea>
                <span asp-validation-for="LocationDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationPostcode" class="control-label"></label>
                <input asp-for="LocationPostcode" class="form-control"/>
                <span asp-validation-for="LocationPostcode" class="text-danger"></span>
            </div>
            @if (User.IsInRole("SuperAdmin"))
            {
                <div class="form-group">
                    <label asp-for="StatusId" class="control-label"></label>
                    <select asp-for="StatusId" class="form-control" asp-items="ViewBag.Statuses"></select>
                </div>                
            }
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Wellbeing.Data.Client/Views/Activities/HIstory.cshtml
@using System.Data.Common
@model List<ActivityHistoryViewModel>

@{
    ViewData["Title"] = "Activities/Services";
    var activityId = ViewBag.ActivityId;
    var sourceActionEdit = ViewBag.SourceActionEdit;
}

<ul class="nav nav-tabs">
    @if (sourceActionEdit)
    {
        <li class="nav-item">
            <a class="nav-link" asp-action="Edit" asp-controller="Activities" asp-route-id="@activityId">General</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-action="HistoryEdit" asp-controller="Activities" asp-route-id="@activityId">History</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-action="Details" asp-controller="Activities" asp-route-id="@activityId">General</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-action="HistoryDetails" asp-controller="Activities" asp-route-id="@activityId">History</a>
        </li>
    }

</ul>


<h2 class="details-header">Activities/History</h2>

<div class="table-responsive-sm activityList">

    <table class="table table-bordered">
        <thead>
            <tr class="activity-header">
                <th style="width: 15%">
                    Description
                </th>
                <th style="width: 15%">
                    Notified
                </th>
                <th style="width: 40%">
                    Recipients
                </th>
                <th style="width: 15%">
                    User
                </th>
                <th style="width: 15%">
                    Date record created
                </th>
            </tr>
        </thead>
        <tbody>        
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NotificationSent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Recipients)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedByUser)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

src/Wellbeing.Data.Client/Views/Activities/Index.cshtml
@using System.Data.Common
@model PaginationActivitiesDataEntry<ActivityViewModel>

@{
    ViewData["Title"] = "Activities/Services";
}

<h2>Activities/Services</h2>


@using (Html.BeginForm("Index", "Activities", FormMethod.Post))
{
    <div class="activitySearchForm">
           
        <div class="row">
            <div class="col-md-2">
                <label>Search</label>
            </div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Search, new { @class="search-box", placeholder = "Enter search keyword" })
            </div>
            <div class="col-md-1">

            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <label> Event provider Organisation</label>
            </div>
            <div class="col-md-9">
                @Html.DropDownListFor(f => f.EventProviderOrganisationFilter, Model.EventProviderOrganisationList, "<Select>")                
            </div>
            <div class="col-md-1">

            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <label> Data provider Organisation</label>
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(f => f.DataProviderOrganisationFilter, Model.DataProviderOrganisationList, "<Select>")
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <label> Status</label>
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(f => f.StatusFilter, Model.StatusList, "<Select>")
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <label> Activity Type</label>
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(f => f.ActivityTypeFilter, Model.ActivityTypeList, "<Select>")
            </div>
            <div class="col-md-5">
                <input type="submit" value="Search" />
            </div>
            <div class="col-md-1">
                <a asp-action="Create" class="btn btn-secondary btn-sm">Create New</a>
            </div>
        </div>
 </div>
}
    @if(Model.HaveSearched)
    { 
        <div class="activityResultsFound">
           
        </div>
    }
    
<div class="table-responsive-sm activityList">

    <table class="table table-bordered">
        <thead>
            <tr class="activity-header">
                <th style="width: 15%">
                    Primary Activity Type
                </th>
                <th style="width: 15%">
                    Activity Type
                </th>
                <th style="width: 20%">
                    Title
                </th>
                <th style="width: 15%">
                    Provider Organisation
                </th>
                <th style="width: 15%">
                    Contact person
                </th>
                <th style="width: 15%">
                    Date record created
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>        
        @(await Component.InvokeAsync<PagerDataEntryViewComponent>(Model))
        @foreach (var item in Model.ResultSet)
        {
            <tr class="@(item.StatusId == 0 ? "status-draft" : "status-approved")">
                <td>
                    @Html.DisplayFor(modelItem => item.PrimaryClassification.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivityType.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrganisationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>

                    <div class="btn-group dropleft">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdownMenu2">
                            Options
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            <!-- Dropdown menu links -->
                            @if (@item.UserCanEdit)
                            {
                                <a asp-action="Edit" asp-route-id="@item.Id" class="dropdown-item">Edit</a>
                            }

                            <a asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">Details</a>
                            @if (@item.UserCanEdit)
                            {
                            <a asp-action="Delete" asp-route-id="@item.Id" class="dropdown-item">Delete</a>
                            }
                                
                        </div>
                    </div>

                </td>
            </tr>
        }
        </tbody>
    </table>
    @if (Model.RowCount > 0)
    {
        <div class="pager-bottom">
            @(await Component.InvokeAsync<PagerDataEntryViewComponent>(Model))
        </div>
    }
</div>